import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "react-datepicker/dist/react-datepicker-cssmodules.css";
import "react-datepicker/dist/react-datepicker.css";

import NextAuthProvider from "@/plugins/next-auth/provider";
import CustomSWRConfig from "@/plugins/swr";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Boilerplate Nextjs 14 - By @zidane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomSWRConfig>
          <NextAuthProvider>{children}</NextAuthProvider>
        </CustomSWRConfig>
      </body>
    </html>
  );
}
