import type { Metadata } from "next";

import { Inter } from "next/font/google";

import NextAuthProvider from "@/plugins/next-auth/provider";
// import ReactQueryProvider from "@/plugins/react-query/provider";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Boilerplate Nextjs 14 - By @zidane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ReactQueryProvider> */}
        <NextAuthProvider>{children}</NextAuthProvider>
        {/* </ReactQueryProvider> */}
      </body>
    </html>
  );
}
